apiVersion: v1
kind: Service
metadata:
  name: gtoolbox
  namespace: dev
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app.kubernetes.io/name: gtoolbox
  ports:
    - name: "8080"
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtoolbox
  namespace: dev
  labels:
    app.kubernetes.io/name: gtoolbox
    app: gtoolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gtoolbox
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gtoolbox
    spec:
      containers:
      - name: gtoolbox
        image: gcr.io/google-containers/toolbox:20201104-00
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8081
            protocol: UDP
        env:
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "0.1"
            memory: "100M"
          limits:
            cpu: "0.5"
            memory: "0.5Gi"

      restartPolicy: Always