apiVersion: v1
kind: Service
metadata:
  name: busybox
  namespace: dev
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app.kubernetes.io/name: busybox
  ports:
    - name: "80"
      protocol: TCP
      port: 80
      targetPort: 80
    - name: "8081"
      protocol: UDP
      port: 8081
      targetPort: 8081
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: dev
  labels:
    app.kubernetes.io/name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: busybox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: busybox
    spec:
      containers:
      - name: busybox
        image: yauritux/busybox-curl:latest
        command: [ "/bin/sh", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 8081
            protocol: UDP