apiVersion: v1
kind: Service
metadata:
  name: network-multitool
  namespace: dev
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app.kubernetes.io/name: network-multitool
  ports:
    - name: "8080"
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: "8081"
      protocol: UDP
      port: 8081
      targetPort: 8081
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-multitool
  namespace: dev
  labels:
    app.kubernetes.io/name: network-multitool
    app: network-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: network-multitool
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: network-multitool
    spec:
      containers:
      - name: network-multitool
        image: wbitt/network-multitool:alpine-extra
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8081
            protocol: UDP
        env:
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        resources:
          requests:
            cpu: "0.1"
            memory: "100M"
          limits:
            cpu: "0.5"
            memory: "0.5Gi"

      restartPolicy: Always